version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  notify_slack:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run:
          command: |
            curl -X POST -H 'Content-type: application/json' --data '{"text":"New Build Tools Release","blocks":[{"type":"header","text":{"type":"plain_text","text":"New Build Tools Release"}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Version:* ${CIRCLE_TAG}"}]}]}' ${SLACK_WEBHOOK}
  self_test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: |
            cd ./example-site/
            node ./../src/cli.js build test-plugin,test-theme --once | tee projects-output.txt
            echo "Test ouput"
            [[ $(grep "\* .*\[.*\/package.json\]" projects-output.txt -c) =~ "2" ]] || exit 1
          name: Run test - build projects
      - run:
          command: |
            cd ./example-site/
            node ./../src/cli.js build --site --once | tee site-output.txt
            echo "Test ouput"
            [[ $(grep "\* .*\[.*\/package.json\]" site-output.txt -c) =~ "3" ]] || exit 1
          name: Run test - build site
      - run:
          command: |
            cd ./example-site/plugins/test-plugin/
            node ./../../../src/cli.js build --once | tee ../../single-output.txt
            echo "Test output"
            [[ $(grep "\* .*\[.*\/package.json\]" ../../single-output.txt -c) =~ "1" ]] || exit 1
          name: Run test - build single
      - run:
          command: |
            cd ./example-site/
            rm *-output.txt
          name: Clean up
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_build_tools:
    jobs:
      - self_test
  run_notify_slack:
    jobs:
      - notify_slack:
          filters:
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+(-(rc|beta|alpha).[0-9]+)?$/i
