version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  install_tests:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - restore_cache:
          name: Restoring Modules Cache
          keys:
            - v1-modules-cache-{{ checksum "package-lock.json" }}
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: |
            cd ./example-site/
            node ./../src/cli.js install
          name: Run test - install projects
      - run:
          command: |
            cd ./example-site/
            node ./../src/cli.js install -- --package-lock-only
          name: Run test - install projects with npm args
      - run:
          command: |
            cd ./example-site/
            node ./../src/cli.js ci
          name: Run test - ci install projects
      - save_cache:
          name: Saving Modules Cache
          key: v1-modules-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - /home/circleci/.cache
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  self_tests:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - restore_cache:
          name: Restoring Modules Cache
          keys:
            - v1-modules-cache-{{ checksum "package-lock.json" }}
      - run:
          command: |
            cd ./example-site/
            node ./../src/cli.js ci
          name: Run test - ci install projects
      - run:
          command: |
            cd ./example-site/
            node ./../src/cli.js build test-plugin,test-theme --once
          name: Run test - build projects
      - run:
          command: |
            cd ./example-site/
            node ./../src/cli.js build --site --once
          name: Run test - build site
      - run:
          command: |
            cd ./example-site/plugins/test-plugin/
            node ./../../../src/cli.js build --once
          name: Run test - build single
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  node_tests:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - restore_cache:
          name: Restoring Modules Cache
          keys:
            - v1-modules-cache-{{ checksum "package-lock.json" }}
      - run:
          command: |
            cd ./example-site/
            node ./../src/cli.js ci
          name: Run test - ci install projects
      - node/install:
          node-version: '12'
      - run:
          command: |
            cd ./example-site/
            node ./../src/cli.js build test-plugin,test-theme --once
          name: Run test - build projects
      - node/install:
          node-version: '14'
      - run:
          command: |
            cd ./example-site/
            node ./../src/cli.js build test-plugin,test-theme --once
          name: Run test - build projects
      - node/install:
          node-version: '16'
      - run:
          command: |
            cd ./example-site/
            node ./../src/cli.js build test-plugin,test-theme --once
          name: Run test - build projects

workflows:
  test_install:
    jobs:
      - install_tests
  test_build:
    jobs:
      - self_tests
  test_node:
    jobs:
      - node_tests