version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  self_test: # this can be any name you choose
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: |
            cd ./test-project/project/
            node ./../../src/cli.js --site --once
          name: Run test projects - site
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_build_tools:
    jobs:
      - self_test